### PR TITLE
2020 05 15

### PR DESCRIPTION
**Pull request by pdhammond42**

### CODE REVIEW

**Comment by david-humble** [comment]
> Hi David,
> not sure if this is the appropriate forum for responding but it seem sensible.
> Thanks very much for contributing printing, it looks like you have put a lot of effort into that and it has been a clear missing feature for a while.
> Also reversing the count of shafts has been something I have been meaning to do.
> 
> There are a few issues with it before I pull it into master. I spent quite some time removing all the Netbeans form generation, for a number of reasons. The main one is, I don't use Netbeans, and IntelliJ won't even open the .form file as text (I suspect I am missing something,but still).
> You don't seem to have added any unit or UI tests.
> While you are reversing the shafts, can you also reverse the picks?
> Apart form that, thanks again.
> Pete.

Hi Pete I'll see if I can de-automate the form generation and recommit -
 I'll also look into some tests ( I'm an engineer by day and write small things to solve little problems for me so I have always worked in a very informal way (-: )

Can you show me a reference ( or mark up a picture ) to show what you want for reversing the picks before I go off and do things.   It wont be to difficult to difficult to do.  the longer bit is reworking the tests to differentiate between draft based and grid based numbering when setting/ reading cells

**Comment by david-humble** [comment]
Hi Pete
More research/googling/youtubing and I think it is the ends taht need to be redone -  

ends  1 . . e right to left 

picks 1 . .  p top to bottom  ( as is )

harnesses 1 . . >  h bottom to top ( done)

I'll get going on this next

**Comment by pdhammond42** [comment]
I think there are two schools off thought with pick numbering. There probably are, there are with most things in weaving. Perhaps we should make it an option. When weaving the first pick thrown is at the bottom of the fabric as you look at it, and Anne Dixon in Handweaver's Pattern Book numbers upwards. Good spot on the ends numbering though,

**Comment by pdhammond42** [comment]
I've pulled your changes into my master and made a few tweaks.
I noticed tabs and spaces were getting misaligned so I've autoformatted everyth ing. Consequently you might see a lot of apparent changes. Can you make sure your editor is set to 4 space indents, no tabs. Thanks

**Comment by david-humble** [comment]
Will look my settings 
Re ends ,  This one is interesting ,  I agree that end 1 at bottom seems better , and that if you weave per the numbering you might get a mirror image of the pattern.  
This is the clearest definition ( just found) [Draft Forms ](https://warpedforgood.com/2017/03/tools-day-Swedish-weaving-draft/) and this defines out layout top to bottom.

Ill do a check to verify how we match this definition

**Comment by david-humble** [comment]
Hi Pete I cant see my additions with your tweaks and tidying on the repository.  I'm having new ideas and would like to start from the new master

**Comment by pdhammond42** [comment]
You're right, nor can I. I must have failed or forgotten to push. I'll look into it tomorrow. 

⁣Sent from Blue ​

**Pull request closed without merging**
